#!/bin/bash
make -f eegllib.mak
make -f etauslib.mak
make -f libvis.mak
make -f eegldots.mak
make -f etausdots.mak
make -f fibodots.mak
make -f lfsrdots.mak
make -f sinedots.mak
make -f rudots.mak
make -f sranddots.mak
make -f gsldots.mak
make -f eeglgen.mak
make -f etausgen.mak
make -f rugen.mak
make -f fibogen.mak
make -f lfsrgen.mak
make -f sinegen.mak
make -f srandgen.mak
make -f gslgen.mak
make -f gendie.mak
make -f diedots.mak
